name: smart_attend
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2

  flutter_blue_plus: ^1.36.8
  flutter_ble_peripheral: ^1.2.5
  permission_handler: ^12.0.3

  uuid: ^4.5.1
  
  excel: ^4.0.6
  pdf: ^3.11.1
  printing: ^5.13.4
  path_provider: ^2.1.5
  open_filex: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

dependency_overrides:
  path_provider_foundation: 2.4.0

flutter:

  uses-material-design: true


